### ISSUE TITLE
decrypt failed

### ISSUE THREAD

**Issue by matishsiao** [ssdb/phpssdbadmin#14]
使用最新版本的ssdbadmin,登入後出現decrypt failed error
decrypt failed

/var/www/html/phpssdbadmin/app/controllers/login.php:42 _throw()
/var/www/html/phpssdbadmin/app/controllers/login.php:20 on_submit()
/var/www/html/phpssdbadmin/iphp/framework/App.php:103 index()
/var/www/html/phpssdbadmin/iphp/framework/App.php:47 execute()
/var/www/html/phpssdbadmin/index.php:9 run()

**Comment by ideawu** [comment]
Hi, 请问你是不是没有安装 php-mcrypt 模块?

**Comment by matishsiao** [comment]
沒安裝...裝完就可以了
感謝
