### ISSUE TITLE
不改密码就是“can not login”，改了密码就是“get_encrypt_keys failed"

### ISSUE THREAD

**Issue by markqiu** [ssdb/phpssdbadmin#21]
php版本 5

错误信息：
get_encrypt_keys failed

/var/www/html/app/classes/SafeUtil.php:70 _throw()
/var/www/html/app/controllers/login.php:24 create_encrypt_info()
/var/www/html/iphp/framework/App.php:166 index()
/var/www/html/iphp/framework/App.php:153 execute()
/var/www/html/iphp/framework/App.php:80 _run()
/var/www/html/index.php:9 run()

**Comment by markqiu** [comment]
在php 7 下ok，难道是必须要php 7?

**Comment by ideawu** [comment]
应该是 openssl 模块没有安装对.

**Comment by PleijaNet** [comment]
https://stackoverflow.com/questions/17272809/openssl-pkey-export-and-cannot-get-key-from-parameter-1/18869750#18869750
