### ISSUE TITLE
显示不了验证码，请问是什么问题？

### ISSUE THREAD

**Issue by dming519** [ssdb/phpssdbadmin#23]
decrypt failed
/usr/share/nginx/html/phpssdbadmin/app/controllers/login.php:42 _throw()
/usr/share/nginx/html/phpssdbadmin/app/controllers/login.php:20 on_submit()
/usr/share/nginx/html/phpssdbadmin/iphp/framework/App.php:166 index()
/usr/share/nginx/html/phpssdbadmin/iphp/framework/App.php:153 execute()
/usr/share/nginx/html/phpssdbadmin/iphp/framework/App.php:80 _run()
/usr/share/nginx/html/phpssdbadmin/index.php:9 run()

**Comment by ideawu** [comment]
文档有安装步骤，php模块要求等。
