### ISSUE TITLE
登陆成功后ssdb连接不上

### ISSUE THREAD

**Issue by huaxiaoer** [ssdb/phpssdbadmin#26]
SSDB error: 13: Permission denied
/var/www/html/phpssdbadmin/app/classes/BaseController.php:49 _throw()
/var/www/html/phpssdbadmin/iphp/framework/App.php:162 init()
/var/www/html/phpssdbadmin/iphp/framework/App.php:153 execute()
/var/www/html/phpssdbadmin/iphp/framework/App.php:80 _run()
/var/www/html/phpssdbadmin/index.php:9 run()

用ssdb-cli 工具同样的ip和port 可以连接成功

**Comment by LanceLiang81** [comment]
操作系统设置问题，我的是CentOS,执行以下命令就可以了：
**setsebool -P httpd_can_network_connect 1**
