### ISSUE TITLE
Cannot redeclare class SimpleSSDB

### ISSUE THREAD

**Issue by skiy** [ssdb/phpssdbadmin#4]
2015/03/17 11:13:16 [error] 54437#0: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare class SimpleSSDB in /home/www/phpssdbadmin/app/classes/SimpleSSDB.php on line 20" while reading response header from upstream, client: 192.168.1.101, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "192.168.1.100:85"

环境是nginx+ubuntu

**Comment by ideawu** [comment]
你是否个性过 phpssdbadmin 的代码? 我这里测试没有问题, 你先自己查一下.

**Comment by skiy** [comment]
没有。是新建一个ssdb.conf到sites-enabled里面，端口85。
另外ssdb.conf改成了
```
location /{
    try_files $uri $uri/ /index.php?$args;
}
```
192.168.1.100:85/login 可以登陆，登陆成功后会白屏，查看了下是500错误。然后再看nginx的error.log文件，发现是标题说的错误~

PS：代码没有改过。我在本地用该文件使用apache配置的时候加config.php里面的ip改成192.168.1.100 可以连接，但将该源码上传到ubuntu就出现我说的错误了。

**Comment by ideawu** [comment]
我下载了最新的代码, 没有发现此问题. 请你仔细检查一下, 例如在 php 代码里 echo 一些特殊的字符, 确认你访问的代码是最新的.

**Comment by skiy** [comment]
应该是最新的源码。我刚刚又重新下了。依然是这个问题~不知道是不是和php环境有关。```PHP Version 5.5.9```Ubuntu + Nginx1.4.6

```
2015/03/17 13:38:35 [error] 54438#0: *343 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/www/phpssdbadmin/app/views/_header.tpl.php on line 30" while reading response header from upstream, client: 192.168.1.103, server: localhost, request: "GET /phpssdbadmin/login HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "192.168.1.130"
2015/03/17 13:38:45 [error] 54438#0: *343 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare class SimpleSSDB in /home/www/phpssdbadmin/app/classes/SimpleSSDB.php on line 20" while reading response header from upstream, client: 192.168.1.103, server: localhost, request: "GET /phpssdbadmin/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "192.168.1.130", referrer: "http://192.168.1.130/phpssdbadmin/login"

```

**Comment by skiy** [comment]
已经解决。pull request上去了~
